#if ! defined( PARTIDA_ )
#define PARTIDA_

/***************************************************************************
*  $MCD Módulo de definição: PAR  Partida
*
*  Arquivo gerado:              PARTIDA.c
*  Letras identificadoras:      PAR
*
*  Projeto: INF 1301 / FreeCell
*  Autores: Miguel Corti
***************************************************************************/

#if defined( PARTIDA_OWN )
   #define PARTIDA_EXT
#else
   #define PARTIDA_EXT extern
#endif

/***** Declaracoes exportadas pelo modulo *****/










#undef PARTIDA_EXT

#else
#endif