# Teste do módulo coluna visível usando a biblioteca contendo o arcabouço

[Diretorios]

Nome        =  TesteCV
PathDefault =  ..\Fontes
err         =  ..\Produto
obj         =  ..\Objetos
c           =  ..\Fontes
h           =  ..\Fontes
def         =  ..\Tabelas

[Modulos]
Lista
Baralho
ColunaVisivel
TestCV

[BuildInicio]
/OUT:..\produto\TesteCV.exe
/INCREMENTAL:NO
/MACHINE:IX86

[BuildFim]
ArcaboucoTeste.lib

[Fim]
